name: Example Workflows

on:
  workflow_dispatch:

jobs:
  # Example 1: Install binstaller itself
  example-binstaller:
    name: Install binstaller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install binstaller
        uses: binary-install/setup-x@v1
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/main/install.sh
          gh_attestations_verify_flags: --repo binary-install/binstaller --cert-identity-regex=.github/workflows/generate-installer.yml@refs/heads/main
      
      - name: Run binstaller
        run: |
          binst --version
          binst help

  # Example 2: Install with SHA256 verification (pinned version)
  example-sha256-verification:
    name: Install with SHA256 verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # SHA256 hash pre-calculated for the specific commit
      # curl -sL https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh | sha256sum
      - name: Install binstaller with SHA256 verification
        uses: binary-install/setup-x@v1
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh
          script_sha256: a9e4bd9c9b9e311b8649afdb63352c8a48a48aaae19d0dd6699510ac14e30c04
          version: v0.0.7
      
      - name: Verify installation
        run: |
          binst --version
          binst help

  # Example 3: Cross-platform installation
  example-cross-platform:
    name: Cross-platform binstaller Installation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install binstaller (cross-platform)
        uses: binary-install/setup-x@v1
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh
          version: v0.0.7
      
      - name: Test tool on ${{ matrix.os }}
        run: |
          binst --version
          binst help