name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-basic:
    name: Test Basic Installation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Test with binstaller installer (pinned version)
        uses: ./
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh
          version: v0.0.7
      
      - name: Verify installation
        run: |
          which binst
          binst --version

  test-with-sha256:
    name: Test with SHA256 Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download script and calculate SHA256
        id: prepare
        run: |
          SCRIPT_URL="https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh"
          curl -fsSL "$SCRIPT_URL" -o install.sh
          SHA256=$(sha256sum install.sh | cut -d' ' -f1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
      
      - name: Install with SHA256 verification
        uses: ./
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/583937e442237ddbc4e2d6277f8176f4750d97ef/install.sh
          script_sha256: ${{ steps.prepare.outputs.sha256 }}
      
      - name: Verify installation
        run: binst --version

  test-gh-attestation:
    name: Test with GitHub Attestation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install with gh attestation verify (main branch)
        uses: ./
        with:
          script_url: https://raw.githubusercontent.com/binary-install/binstaller/main/install.sh
          gh_attestations_verify_flags: --repo binary-install/binstaller --cert-identity-regex=.github/workflows/generate-installer.yml@refs/heads/main
      
      - name: Verify installation
        run: |
          which binst
          binst --version

